<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns1="http://xmlns.schneider.com/EnterpriseObjects/Common/HumanTask/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://xmlns.schneider.com/EnterpriseObjects/Core/Common/V1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:client="http://xmlns.oracle.com/SOA_Application1/FndIntgHumanTaskIVP/FndIntgHumanTaskStatusUpdate" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns1 ns0 client plnk xsd wsdl bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../FndIntgHumanTaskStatusUpdate.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ManageHumanTaskRequest" namespace="http://xmlns.schneider.com/EnterpriseObjects/Common/HumanTask/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../FndIntgHumanTaskStatusUpdate.wsdl"/>
            <oracle-xsl-mapper:rootElement name="payload" namespace=""/>
            <oracle-xsl-mapper:rootElementDatatype name="ManageHumanTaskRequestType" namespace="http://xmlns.schneider.com/EnterpriseObjects/Common/HumanTask/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [WED OCT 04 06:47:18 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <payload>
      <ns0:SNIHeader>
        <ns0:MessageID>
          <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:MessageID"/>
        </ns0:MessageID>
        <ns0:MessageName>
          <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:MessageName"/>
        </ns0:MessageName>
        <xsl:if test="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:BusinessKey">
          <ns0:BusinessKey>
            <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:BusinessKey"/>
          </ns0:BusinessKey>
        </xsl:if>
        <xsl:if test="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:SessionID">
          <ns0:SessionID>
            <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:SessionID"/>
          </ns0:SessionID>
        </xsl:if>
        <ns0:CreatedDateTime>
          <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:CreatedDateTime"/>
        </ns0:CreatedDateTime>
        <xsl:if test="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:RequestMessageID">
          <ns0:RequestMessageID>
            <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:RequestMessageID"/>
          </ns0:RequestMessageID>
        </xsl:if>
        <ns0:Sender>
          <xsl:if test="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Sender/ns0:Name">
            <ns0:Name>
              <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Sender/ns0:Name"/>
            </ns0:Name>
          </xsl:if>
          <xsl:if test="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Sender/ns0:ApplicationName">
            <ns0:ApplicationName>
              <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Sender/ns0:ApplicationName"/>
            </ns0:ApplicationName>
          </xsl:if>
          <xsl:if test="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Sender/ns0:HostName">
            <ns0:HostName>
              <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Sender/ns0:HostName"/>
            </ns0:HostName>
          </xsl:if>
          <xsl:if test="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Sender/ns0:InstanceID">
            <ns0:InstanceID>
              <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Sender/ns0:InstanceID"/>
            </ns0:InstanceID>
          </xsl:if>
          <xsl:if test="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Sender/ns0:UserID">
            <ns0:UserID>
              <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Sender/ns0:UserID"/>
            </ns0:UserID>
          </xsl:if>
        </ns0:Sender>
        <ns0:Target>
          <xsl:if test="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Target/ns0:Name">
            <ns0:Name>
              <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Target/ns0:Name"/>
            </ns0:Name>
          </xsl:if>
          <xsl:if test="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Target/ns0:ApplicationName">
            <ns0:ApplicationName>
              <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Target/ns0:ApplicationName"/>
            </ns0:ApplicationName>
          </xsl:if>
          <xsl:if test="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Target/ns0:EndPointURI">
            <ns0:EndPointURI>
              <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:Target/ns0:EndPointURI"/>
            </ns0:EndPointURI>
          </xsl:if>
        </ns0:Target>
        <ns0:HeaderExtension>
          <xsl:if test="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:HeaderExtension/ns0:Value">
            <xsl:for-each select="/ns1:ManageHumanTaskRequest/ns0:SNIHeader/ns0:HeaderExtension/ns0:Value">
              <ns0:Value>
                <xsl:if test="@Name">
                  <xsl:attribute name="Name">
                    <xsl:value-of select="@Name"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="."/>
              </ns0:Value>
            </xsl:for-each>
          </xsl:if>
        </ns0:HeaderExtension>
      </ns0:SNIHeader>
      <ns1:KeyData1>
        <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns1:KeyData1"/>
      </ns1:KeyData1>
      <ns1:KeyData2>
        <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns1:KeyData2"/>
      </ns1:KeyData2>
      <ns1:KeyData3>
        <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns1:KeyData3"/>
      </ns1:KeyData3>
      <ns1:TaskDefinitionNames>
        <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns1:TaskDefinitionNames"/>
      </ns1:TaskDefinitionNames>
      <ns1:Operation>
        <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns1:Operation"/>
      </ns1:Operation>
      <ns1:UserId>
        <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns1:UserId"/>
      </ns1:UserId>
      <ns1:PassWord>
        <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns1:PassWord"/>
      </ns1:PassWord>
      <ns1:UpdateData>
        <xsl:value-of select="/ns1:ManageHumanTaskRequest/ns1:UpdateData"/>
      </ns1:UpdateData>
    </payload>
  </xsl:template>
</xsl:stylesheet>