<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://siebel.com/webservices" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:client="http://xmlns.schneider.com/SNIFndIntgIVPServices/FndIntgSiebelSecIVP/FndIntgSiebelSecIVP" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsdLocal1="http://www.siebel.com/xml/SNI%20Order%20Revisions/Data" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:tns="http://siebel.com/asi/" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl plnk client wsdl xsd ns0 soapenc soap xsdLocal1 tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../FndIntgSiebelSecIVP.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Revisions_Input" namespace="http://xmlns.schneider.com/SNIFndIntgIVPServices/FndIntgSiebelSecIVP/FndIntgSiebelSecIVP"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../SNISiebelOrderCheckOpenRevisions.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Revisions_Input" namespace="http://siebel.com/asi/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU OCT 05 03:59:14 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <tns:Revisions_Input>
      <xsdLocal1:ListOfSniOrderRevisions>
        <xsl:attribute name="lastpage">
          <xsl:value-of select="/client:Revisions_Input/client:ListOfSniOrderRevisions/@lastpage"/>
        </xsl:attribute>
        <xsl:attribute name="recordcount">
          <xsl:value-of select="/client:Revisions_Input/client:ListOfSniOrderRevisions/@recordcount"/>
        </xsl:attribute>
        <xsl:for-each select="/client:Revisions_Input/client:ListOfSniOrderRevisions/client:SniOrderLineItem-Billing">
          <xsdLocal1:SniOrderLineItem-Billing>
            <xsdLocal1:SNIBatchNum>
              <xsl:value-of select="client:SNIBatchNum"/>
            </xsdLocal1:SNIBatchNum>
            <xsdLocal1:SNIInvoiceGroupKey>
              <xsl:value-of select="client:SNIInvoiceGroupKey"/>
            </xsdLocal1:SNIInvoiceGroupKey>
            <xsdLocal1:SNIOrderActiveStatus>
              <xsl:value-of select="client:SNIOrderActiveStatus"/>
            </xsdLocal1:SNIOrderActiveStatus>
            <xsdLocal1:SNIOrderHeaderId>
              <xsl:value-of select="client:SNIOrderHeaderId"/>
            </xsdLocal1:SNIOrderHeaderId>
          </xsdLocal1:SniOrderLineItem-Billing>
        </xsl:for-each>
      </xsdLocal1:ListOfSniOrderRevisions>
    </tns:Revisions_Input>
  </xsl:template>
</xsl:stylesheet>