<wsdl:definitions
     name="FndIntgHeaderXPathImpl"
     targetNamespace="http://xmlns.oracle.com/SNIFndIntgIVP_jws/FndIntgHeaderXPath/FndIntgHeaderXPathImpl"
     xmlns:ns1="http://xmlns.schneider.com/EnterpriseObjects/Core/Common/V1"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/SNIFndIntgIVP_jws/FndIntgHeaderXPath/FndIntgHeaderXPathImpl"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="FndIntgHeaderXPathImpl">
        <plnk:role name="FndIntgHeaderXPathImplProvider">
            <plnk:portType name="client:FndIntgHeaderXPathImpl"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/SNIFndIntgIVP_jws/FndIntgHeaderXPath/FndIntgHeaderXPathImpl"
                 schemaLocation="oramds:/apps/SNIComponents/FoundationObjectLibrary/IVP/schemas/FndIntgHeaderXPathImpl.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.schneider.com/EnterpriseObjects/Core/Common/V1" schemaLocation="oramds:/apps/SNIComponents/EnterpriseObjectLibrary/Core/Common/V1/SNICore.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="FndIntgHeaderXPathImplRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="FndIntgHeaderXPathImplResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="FndIntgHeaderXPathImpl">
        <wsdl:operation name="process">
            <wsdl:input message="client:FndIntgHeaderXPathImplRequestMessage"/>
            <wsdl:output message="client:FndIntgHeaderXPathImplResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
