<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="FndIntgFaultHandleBPEL"
     targetNamespace="http://xmlns.oracle.com/SNIFndIntgIVPServices/FndIntgFaultHandlingIVP/FndIntgFaultHandleBPEL"
     xmlns:ns1="http://xmlns.schneider.com/EnterpriseObjects/Core/Common/V1"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/SNIFndIntgIVPServices/FndIntgFaultHandlingIVP/FndIntgFaultHandleBPEL"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="FndIntgFaultHandleBPEL">
        <plnk:role name="FndIntgFaultHandleBPELProvider">
            <plnk:portType name="client:FndIntgFaultHandleBPEL"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://xmlns.schneider.com/EnterpriseObjects/Core/Common/V1"
             xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://xmlns.oracle.com/SNIFndIntgIVPServices/FndIntgFaultHandlingIVP/FndIntgFaultHandleBPEL"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
            <import namespace="http://xmlns.oracle.com/SNIFndIntgIVPServices/FndIntgFaultHandlingIVP/FndIntgFaultHandleBPEL"
                 schemaLocation="oramds:/apps/SNIComponents/FoundationObjectLibrary/IVP/schemas/FndIntgFaultHandleBPEL.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://xmlns.schneider.com/EnterpriseObjects/Core/Common/V1"
             xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://xmlns.oracle.com/SNIFndIntgIVPServices/FndIntgFaultHandlingIVP/FndIntgFaultHandleBPEL"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
            <xsd:import namespace="http://xmlns.schneider.com/EnterpriseObjects/Core/Common/V1" schemaLocation="oramds:/apps/SNIComponents/EnterpriseObjectLibrary/Core/Common/V1/SNICore.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="FndIntgFaultHandleBPELRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="FndIntgFaultHandleBPELResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="FndIntgFaultHandleBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:FndIntgFaultHandleBPELRequestMessage"/>
            <wsdl:output message="client:FndIntgFaultHandleBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
