<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="FndIntgSOAToOSBIntg"
     targetNamespace="http://xmlns.schneider.com/SNIFndSOAIVPServices/FndIntgSOAToOSBIntg/FndIntgSOAToOSBIntg"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:WL5G3N1="http://xmlns.schneider.com/SNIFndSOAIVPServices/FndIntgSOAToOSBIntg/FndIntgSOAToOSBIntg"
    >
    <plnk:partnerLinkType name="OSBServiceInt">
        <plnk:role name="FndIntgSOAToOSBIntg">
            <plnk:portType name="WL5G3N1:FndIntgSOAToOSBIntg"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.schneider.com/SNIFndSOAIVPServices/FndIntgSOAToOSBIntg/FndIntgSOAToOSBIntg"
         location="oramds:/apps/SNIComponents/FoundationServiceLibrary/IVP/FndIntgSOAToOSBIntg.wsdl"/>
</wsdl:definitions>
