<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ChkXpathSOAIVP"
     targetNamespace="http://xmlns.schneider.com/SNIFndIntgIVPServices/ChkXpathSOAIVPSvc"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:tns="http://xmlns.schneider.com/SNIFndIntgIVPServices/ChkXpathSOAIVPSvc"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="FndIntgValidateXpathFunctionIVP">
        <plnk:role name="ChkXpathSOAIVPPortType">
            <plnk:portType name="tns:ChkXpathSOAIVPPortType"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.schneider.com/SNIFndIntgIVPServices/ChkXpathSOAIVPSvc"
         location="oramds:/apps/SNIComponents/FoundationServiceLibrary/IVP/ChkXpathSOAIVP.wsdl"/>
</wsdl:definitions>
